apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-d
  labels: 
    app: order-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 0
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: nghiahuynh/order-service:1.0
        ports: 
        - containerPort: 6060
        # readinessProbe:
        #   httpGet:
        #      path: /sum?a=1&b=2
        #      port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: order-service-s
spec:
  type: NodePort
  selector:
    app: order-service
  ports:
  - port: 6060