apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubiid-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubiid-api
  template:
    metadata:
      labels:
        app: ubiid-api
    spec:
      containers:
        - name: ubiid-api
          image: docker.ubitec.io/io.ubitec/ubiid/ubiid-api:1.4.0-SNAPSHOT
          ports:
            - containerPort: 5432
      imagePullPolicy: Always
      imagePullSecrets:
        - name: nghia-s

---
apiVersion: v1
kind: Service
metadata:
  name: ubiid-api-service
spec:
  selector:                  
    app: ubiid-api
  type: NodePort
  ports:
  - nodePort: 32000
    port: 8080          
    protocol: TCP
    targetPort: 8080         